### ISSUE TITLE
ERROR:gpu_init.cc(481) Passthrough is not supported, GL is disabled, ANGLE is

### ISSUE THREAD

**Issue by limitx0** [JacobLinCool/TheatreX#15]
I ran `npx threatrex` on PowerShell, and I got `500 Unexpected Error! You can report this error with the following ID: 31aaf2c994ae437a8b895131c984f4eb` when I visited `http://localhost:3000/`. 

At the same time, `[16000:0126/190347.894:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is` was on terminal output. 

I use: 
theatrex@1.0.0-dev.19
Windows 11
PowerShell 7.3.1
Node.js v18.13.0

**Comment by JacobLinCool** [comment]
This is a problem of chromium I think and this should not affect the program to run.
